### ISSUE TITLE
Clang does not inherently mean the usage of libc++

### ISSUE THREAD

**Issue by jaynus** [rpclib/rpclib#101]
Currently, the cmake configuration is automatically configured to use libc++ if using clang; this is not the standard case on linux or other environments, where although I may be using clang - I could be using different standard libraries. 

This should be changed to a configurable setting (at most) or just using the system defaults (ideal, I will configure my build environment how I please) - this should not be forcing C++ standard libraries based on compiler in the build script.

**Comment by noc0lour** [comment]
Yep, removing the libc++ `RPC_BUILD_FLAG` resolved the issue for me.

**Comment by sztomi** [comment]
Good point, thanks for raising this issue.

**Comment by sztomi** [comment]
For context, I started this project way back when clang was only viable with libc++, but that changed a long time ago, so yes, this has to be fixed. The fix will be part of 1.0.0.
