### ISSUE TITLE
Error build windows 10, vs2015 update 3 community

### ISSUE THREAD

**Issue by Maxfashko** [rpclib/rpclib#108]
Hello. I used the sample assembly from this video https://www.youtube.com/watch?v=1oY8Qu5maQQ&feature=youtu.be. The following errors occurred during the build (debug x64):

>Error LNK2038 detected a mismatch for "_ITERATOR_DEBUG_LEVEL": value "0" does not match the value "2" in main.obj DroneShell C: \ Users \ maxfa \ Code \ AirSim \ DroneShell \ AirLib.lib (client.obj) 

>Error LNK2038 detected a discrepancy for "RuntimeLibrary": the value of "MD_DynamicRelease" does not match the value of "MDd_DynamicDebug" in main.obj DroneShell C: \ Users \ maxfa \ Code \ AirSim \ DroneShell \ AirLib.lib (client.obj) 1

>Error LNK2038 detected a mismatch for "_ITERATOR_DEBUG_LEVEL": value "0" does not match the value "2" in main.obj DroneShell C: \ Users \ maxfa \ Code \ AirSim \ DroneShell \ AirLib.lib (rpc_error.obj) 1

>Error LNK2038 detected discrepancy for "RuntimeLibrary": MD_DynamicRelease value does not match MDd_DynamicDebug value in main.obj DroneShell C: \ Users \ maxfa \ Code \ AirSim \ DroneShell \ AirLib.lib (rpc_error.obj) 1

>Error LNK2038 detected a mismatch for "_ITERATOR_DEBUG_LEVEL": value "0" does not match the value "2" in main.obj DroneShell C: \ Users \ maxfa \ Code \ AirSim \ DroneShell \ AirLib.lib (response.obj) 1

>Error LNK2038 detected a discrepancy for "RuntimeLibrary": the value of "MD_DynamicRelease" does not match the value of "MDd_DynamicDebug" in main.obj DroneShell C: \ Users \ maxfa \ Code \ AirSim \ DroneShell \ AirLib.lib (response.obj) 1

> Warning LNK4098 default library "MSVCRT" is inconsistent with the use of other libraries; Use the / NODEFAULTLIB parameter: library DroneShell C: \ Users \ maxfa \ Code \ AirSim \ DroneShell \ LINK 1

If you comment out the lines in build.cmd: 

REM msbuild /p:Platform=x64 /p:Configuration=Debug AirSim.sln
REM if ERRORLEVEL 1 goto :buildfailed

Assembly is performed without errors

**Comment by sztomi** [comment]
@Maxfashko did you close this on purpose? The reason you are seeing this problem is that you have a mismatch between rpclib and the airsim builds; one is built in debug mode, while the other isn't. You need to make sure that both are built the same.

**Comment by Maxfashko** [comment]
sztomi, I'm sorry, I accidentally left a message here. Originally it was intended for https://github.com/Microsoft/AirSim. Thank you for the hint.
