### ISSUE TITLE
how to get return type of `call` dynamically ? (say, stringified or via typeid)

### ISSUE THREAD

**Issue by timotheecour** [rpclib/rpclib#113]

**Comment by sztomi** [comment]
Strictly speaking, this is a question for the `msgpack` project, but I'll try my best to answer.

To my best knowledge, you can't get the original type back, unless you store it yourself somehow. But you can ask the msgpack API to answer two things:

  1. Which of the basic msgpack types the object holds (`msgpack::type::NIL`, `msgpack::type::BOOLEAN`, `msgpack::type::POSITIVE_INTEGER` etc.)?
  2. Is the held data convertible to a certain type?

For the first option, you have to get a `msgpack::object&` from the `object_handle` that call returns. Once you have that, you can use they `type` member of `msgpack::object` to get a type id:

```cpp
auto value = client.call("dynamic_func");
switch (value.get().type) {
case msgpack::type::NIL:
    // the value is nil
    break;
case msgpack::type::BOOLEAN:
    // value is boolean
    bool v = value.as<bool>();
    break;
    // .. etc
}
```

The second option requires trying the conversion. Note, that if your object is a composite value, you will have no other choice than this.

```
try {
    auto mything = client.call("dynamic_func").as<thing>();
    // if I reach the next line, mything is of type thing.
}
catch (msgpack::type_error&) {
    // if I'm here, then the return value was not a `thing`
}
```

There still might be a better option to do this, but I'm not aware. You may want to ask the msgpack maintainers, they are nice and responsive. :)
