### ISSUE TITLE
c.set_timeout(std::numeric_limits<int64_t>::max() doesn't work as intended

### ISSUE THREAD

**Issue by timotheecour** [rpclib/rpclib#115]
should work given type(uint64_t get_timeout()) but doesn't: rpc::timeout: Timeout of 9223372036854775807ms while calling RPC function

**Comment by sztomi** [comment]
Can you add compiler/platform details please?

**Comment by sztomi** [comment]
So apparently `std::chrono::milliseconds` takes a "signed integer type of at least 45 bits" ([source](http://en.cppreference.com/w/cpp/chrono/duration)). This means that the function incorrectly takes an unsigned integer.

**Comment by timotheecour** [comment]
Could u hard code -1 to mean infinity and make it int64_t then? Sime and
would work. And imo shd be default

**Comment by sztomi** [comment]
This was released: https://github.com/rpclib/rpclib/releases/tag/v2.1.0
