### ISSUE TITLE
There should be no default timeout

### ISSUE THREAD

**Issue by timotheecour** [rpclib/rpclib#116]
..especially given that it's a breaking change compared to prior this change being introduced
.. and that 5K ms is pretty arbitrary

fix: could use int64_t as type and use -1 as special value for no timeout

**Comment by sztomi** [comment]
Hmm, good point, although not because of breaking. rpclib uses semver, and the major version was correctly bumped when the feature was released. I really don't like special values, maybe something like std::optional will be used, along with a `clear_timeout` function.

**Comment by timotheecour** [comment]
Sure that works too ( then ignore my comment from 1 minute ago)

**Comment by sztomi** [comment]
This was released: https://github.com/rpclib/rpclib/releases/tag/v2.1.0
