### ISSUE TITLE
Binding overloaded function fails silently

### ISSUE THREAD

**Issue by dkozel** [rpclib/rpclib#119]
When bind is called with the same name as a previous function the insert operation on the unordered_map will fail, but the return value is not being checked.

I'm a little split on possible resolutions to this. In my case the overloaded function has a different number of arguments so rpclib can unambiguously decided between the two. However in the case where an overloaded function takes the same number of arguments, but of a different type then I don't think it is possible to disambiguate.

At minimum the call to bind should notify the caller that it fails.

**Comment by dkozel** [comment]
A semi-related topic would be handling of optional arguments. The current callable lambdas and check for number of arguments prevents the use of overloaded functions.

**Comment by sztomi** [comment]
Yes, this is a known issue; I was considering function overloads, but it's a very tricky subject. The best would probably to just not allow overloading (i.e. throw an exception when binding to the same name). Implementing a sensible overload resolution is probably way over my head. Also, it's not necessarily C++ clients talking to C++ servers, so it doesn't really make sense to implement a logic that works for one particular language.

**Comment by sztomi** [comment]
https://github.com/rpclib/rpclib/issues/19

**Comment by sztomi** [comment]
This was released: https://github.com/rpclib/rpclib/releases/tag/v2.1.0
