### ISSUE TITLE
async_call and Python

### ISSUE THREAD

**Issue by lovettchris** [rpclib/rpclib#122]
Previously you pointed to mprpc for Python wrappers, and it works great.  See [AirSim python wrapper](https://github.com/Microsoft/AirSim/blob/master/docs/python.md).  But mprpc doesn't seem to expose "async_call" pattern, which is what we need for AirSim.  Any thoughts on how to solve that?

**Comment by sztomi** [comment]
I think I'd go with the new coroutines features from 3.6. https://docs.python.org/3/library/asyncio-task.html 

If you can't use those for some reason, you have a couple of options still, like gevent or using a different msgpack-rpc implementation for python. For example, [msgpack-rpc-python](https://github.com/msgpack-rpc/msgpack-rpc-python) seems to support async out-of-box.
