### ISSUE TITLE
 Issues with thread_local on OSX

### ISSUE THREAD

**Issue by akakcolin** [rpclib/rpclib#123]
I got an error when buiding on OSX

rpclib/lib/rpc/this_handler.cc:10:12: error: thread-local storage is not supported for the current target
    static thread_local this_handler_t instance;
           ^

clang++3.9

g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by sztomi** [comment]
For some reason Apple used to ship a dumbed-down version of clang that does not support the standard (C++11) `thread_local`. The solution is to either upgrade To xcode 8+ or  install an upstream clang/gcc via homebrew. See: https://stackoverflow.com/a/29929949/140367
