### ISSUE TITLE
how to transfer bin data (image) to server 

### ISSUE THREAD

**Issue by dmcyang163** [rpclib/rpclib#126]
the server side have a algorithm function as：
float calculateFeature(char* imgdata, int len);
that  calulate the image feature,  

and i want to call server the function. how can i to do this

**Comment by sztomi** [comment]
The easiest would be to create a wrapper that takes a `string` or `vector<char>`  because those are types that messagepack serializes as binary.

```cpp
rpc::server s(8080);
s.bind("calculateFeature", [](std::vector<char> const& img) {
  return calculateFeature(img.data(), img.size());
});
```

Closing this, but feel free to continue the thread.

**Comment by dmcyang163** [comment]
Just tried, it's working.
thanks a lot.

**Comment by sytelus** [comment]
In AirSim, one of the core use case of rpclib is transferring images via API calls. I had a user filing an issue that she tried to retrieve 4K image via API call (this is 10MB in size) and performance went down the drain. I don't have exact perf numbers yet however I'm starting to worry about what is the best way to transfer large bin data (~10MB) via rpclib.
