### ISSUE TITLE
msgpack for my custom class

### ISSUE THREAD

**Issue by shakthi-prashanth** [rpclib/rpclib#129]
Dear Team, warm greetings.

I have a library which has many classes. I have a requirement of sending objects of those classes via rpclib.
For. eg:
class Book {
    float price;
    std::string name;
public:
    Book() {}
    Book(std::string _name, float _price) : price {_price}, name {_name} {}
};  
std::vector\<Book\> books;

I wanted to send **books** via rpclib from server to client. Is it possible **without** editing Book class ?
Thanks,
Shakthi

**Comment by sztomi** [comment]
Hi,

Check out [this example](https://github.com/msgpack/msgpack-c/blob/master/example/cpp03/class_non_intrusive.cpp) from the msgpack-cpp implementation. The gist of it is creating non-member adaptor functions that can handle converting to and from msgpack. It is a lot less convenient than the MSGPACK_DEFINE macro. If you don't mind a copy, you might be better off creating types specifically for transport and just converting between `Book` and `BookTransport` (where the latter uses MSGPACK_DEFINE to handle the serialization).

**Comment by sztomi** [comment]
Closing this, but feel free to continue the thread.
