### ISSUE TITLE
this_session is not really per-client

### ISSUE THREAD

**Issue by avdbg** [rpclib/rpclib#137]
Is it possible to get the server_session in handler callback?

**Comment by sztomi** [comment]
There is `rpc::this_session()`, which might help you (example [here](http://rpclib.net/cookbook/#exiting-a-session). Could you describe your use case? Maybe there is something better.

**Comment by avdbg** [comment]
For example, I hope that the client needs to log in to access some of the resources, so I need to save the login status on the server side for each client. Could RPC :: this_session () do it?

**Comment by avdbg** [comment]
Or should I keep a token on the client and pass it to the server in every RPC call?

**Comment by sztomi** [comment]
Technically, `this_session` corresponds to exactly one client session which does not change as long as the client is connected (the physical address of the session object is guaranteed to stay the same). 

But it's possible that your client loses the connection and reconnects, and you would have a different session for the "same" client. The reconnection does not happen automatically: you have to implement that yourself, at least for now. So, if identifying the client is important, I suggest gathering some hardware id on your client and having a login function of some sort where you store this ID associated with the session. Or passing that ID with function calls could work as well. Callbacks for session state changes are coming soon which may help a bit with this. If you have any input on the desired interface, comment here: https://github.com/rpclib/rpclib/issues/117

**Comment by avdbg** [comment]
If without consider of reconnection, how should I use `this_session` to store the data (or identify a client) ? `this_session` seems to have only one `post_exit()` member function. Is there any other examples? Thanks.

**Comment by sztomi** [comment]
I was going to suggest to use the address of the this_session object, but I realized that there is a bug in the implementation (this_session is not really per-client, but should be). So this cannot work right now. I'm changing the title of this issue track this bug. In the meantime, you can work around this with my suggestion above.

**Comment by avdbg** [comment]
It sounds great👍.

**Comment by sztomi** [comment]
In the end, I decided to add an `id()` function to `this_session`. That function returns a guaranteed unique id for the session. More accurately identifying the client is the implementers job.

**Comment by sztomi** [comment]
This has been released in [v2.2.0](https://github.com/rpclib/rpclib/releases/tag/v2.2.0). Please update.
