### ISSUE TITLE
Patch for rpclib to compile without -lsupc++

### ISSUE THREAD

**Issue by sytelus** [rpclib/rpclib#140]
When rcplib gets linked by programs such as Unreal Engine on Linux, you might get error saying "__cxa_thread_atexit" is missing. It seems to be related to the use of "static thread_local" [here in rpclib](https://github.com/rpclib/rpclib/blob/3c0a23da7356bd31ed8a81a76771dade0f8a7b72/lib/rpc/this_handler.cc#L10). See [this answer on SO](https://stackoverflow.com/questions/29322666/undefined-reference-to-cxa-thread-atexitcxxabi-when-compiling-with-libc). This can be solved by either (1) using [this change](https://github.com/kersny/airsim_nvidia_docker/blob/master/rpc_patch.patch)  or (2) finding alternative to thread local. If you are using the patch in (1) then may be we should have a way to turn off this patch by defining macro.

**Comment by sztomi** [comment]
I probably makes sense to apply that patch then, but I wonder if this breaks other environments. Thanks for bringing this to my attention. 

As for an alternative to `thread_local`, that might require some substantial redesigning in the `server_session` which I'd rather stay away from. It's possible to do, but would almost certainly lead to more complicated code.

**Comment by sztomi** [comment]
I did some research and now I understand the problem better. [libsupc++](http://wiki.osdev.org/Libsupcxx) is essentially the barebones c++ support library for gcc . This is an implementation detail; how any compiler implements the C++ standard library is not a concern for rpclib, as long as the implementation complies with the Standard. 

The fact that Unreal Engine on Linux has a problem with this points to a fault in their toolchain setup and should be worked out on their end - `static thread_local` is perfectly valid C++11. The linked [patch](https://github.com/kersny/airsim_nvidia_docker/blob/master/rpc_patch.patch) does not really have a place in rpclib (especially not in that source file). You could (and would be better off) placing that function in a separate source file and avoid patching rpclib altogether if fixing UE is not a possibility (or just link libsupc++).
