### ISSUE TITLE
Let the caller decided C++ version

### ISSUE THREAD

**Issue by sytelus** [rpclib/rpclib#141]
We have out top level CMakeLists.txt which calls rpclib's CMakeLists.txt. Our top level CMakeLists.txt decides the version of C++ to use depending OS and Unreal Engine platform's support. However unfortunately [this code](https://github.com/rpclib/rpclib/blob/3c0a23da7356bd31ed8a81a76771dade0f8a7b72/CMakeLists.txt#L93) in rpclib then overrides it :(.

**Comment by sztomi** [comment]
You can set this variable before calling add_directory, I believe. That said, #94 is ought solve issues like this. I started rpclib when I wasn't very experienced with cmake, so I used a lot of old-style and donwstream-inconsiderate hacks in the CMakeLists file. The intention with #94 is to get rid of that and allow consuming the library as a source directory. I'm closing this in favor of #94.

**Comment by sytelus** [comment]
Nevermind, I think you have already fixed the issue I mentioned in my original post. This fixes it:

https://github.com/rpclib/rpclib/blob/master/include/rpc/config.h#L32

**Comment by sztomi** [comment]
Oh, OK then. config.h is really there to reduce friction for people who just want to copy all headers and not use the install target. To be pedantic, this is incorrect, because cmake does overwrite this header with some values, but reasonable defaults are provided.

**Comment by sytelus** [comment]
Related issue: https://github.com/rpclib/rpclib/issues/159
