### ISSUE TITLE
version.h not found 

### ISSUE THREAD

**Issue by ahoarau** [rpclib/rpclib#143]
There's a cmake issue on the master branch : 
```
cd /home/hoarau/dev
git clone https://github.com/rpclib/rpclib
cd rpclib 
mkdir build ; mkdir install
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install -DRPCLIB_ENABLE_LOGGING=1
make 
make install
```
Results in : 
```
CMake Error at cmake_install.cmake:44 (file):
  file INSTALL cannot find "/home/hoarau/dev/rpclib/build/version.h".
```

This is because `version.h` is generated in `PROJECT_SOURCE_DIR` 
https://github.com/rpclib/rpclib/blob/master/CMakeLists.txt#L203:L205 but install expects it in `PROJECT_BINARY_DIR` https://github.com/rpclib/rpclib/blob/master/CMakeLists.txt#L296

Also, I think you should add `config.h` in `.gitignore`, but that's really not an issue

**Comment by sztomi** [comment]
Oh, thanks for this. I changed the location of the generated file and forgot to update this. However, 

> Also, I think you should add config.h in .gitignore

I won't. The reason is that people are often lazy to really look around and will just copy the include folder. This is somewhat incorrect since this is a generated file, but at the same time having the latest version in it will cover the majority of use cases. Could you change the PRs to point to the dev branch instead?

**Comment by ahoarau** [comment]
There you go #146 

> I won't. The reason is that people are often lazy to really look around and will just copy the include folder. This is somewhat incorrect since this is a generated file, but at the same time having the latest version in it will cover the majority of use cases

Wouldn't it be better then to generate this file to the binary dir (people that just copy the include folder will then have an issue) ?

**Comment by sztomi** [comment]
No, the goal is to reduce friction, i.e. cover the most use-cases correctly. That is why I changed it so the files are generated in the source directory. If the files are not present in the include directory, people will keep opening issues for missing files. :)

**Comment by sztomi** [comment]
Merged the PR, closing.
