### ISSUE TITLE
rpc::detail::async_writer::do_write: Crash when shutting down an invalid socket

### ISSUE THREAD

**Issue by klemen-forstneric** [rpclib/rpclib#151]
In some cases the `ip::tcp::socket` that's contained within `rpc::detail::async_writer` becomes invalid and calling `shutdown` and `close` on it, crashes the server. [Here seems to be the problem](https://github.com/rpclib/rpclib/blob/master/include/rpc/detail/async_writer.h#L50). Removing lines from 50 to 55 avoids the crash.

I'm curious though, how come you call `shutdown` and `close` on the socket manually? After all, any acquired resources get released in `~socket`.

P.S.: Awesome library! 👍

**Comment by sztomi** [comment]
Oh I wish I opened this before #153 - this is a duplicate :)

`shutdown` is called for portable closing behavior of the socket.
