### ISSUE TITLE
Update msgpack

### ISSUE THREAD

**Issue by sytelus** [rpclib/rpclib#152]
Looks like rpclib has old implementation of msgpack which has few critical issues. For example, serializing some structs with zero size vectors causes runtime errors. This seems to have been [fixed ](https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/v1/adaptor/vector_unsigned_char.hpp#L34)in latest version.

It would be great if msgpack is updated to get these fixes!

**Comment by sztomi** [comment]
Fixed in 81c8334

**Comment by sztomi** [comment]
This has been released in [v2.2.0](https://github.com/rpclib/rpclib/releases/tag/v2.2.0). Please update.
