### ISSUE TITLE
Server exception on client timeout

### ISSUE THREAD

**Issue by xaxousis** [rpclib/rpclib#153]
If a client `call` times out, the server raises a `std::system_error` when trying to write the answer.

I'm not sure whether this should be silently caught by the server or if an interface to handle this type of error should be created.

A temporary workaround is to increase the client timeout, which doesn't resolve the problem if the client quits. When the `run` function of the server is used, the exception can be caught and the server restarted, which is not the case with the `asyn_run` function.

Note: I tried using `rpc::server::suppress_exceptions` but this only catches exceptions from within the bound callbacks.

The following is a minimal example.

**Compilation and run**

Running on Linux (Mint, 18.2).

`server`
```
$ clang++ server.cpp -o server -Iinclude -Llib -std=c++14 -lrpc -lpthread
$ ./server
terminate called after throwing an instance of 'std::system_error'
  what():  shutdown: Bad file descriptor
Abandon
```

`client`
```
$ clang++ client.cpp -o client -Iinclude -Llib -std=c++14 -lrpc -lpthread
$ ./client 
rpc::timeout: Timeout of 50ms while calling RPC function 'bug'
```

**Sources**
`server.cpp`
```c++
#include <thread>
#include <chrono>

#include "rpc/server.h"

int main() {

  rpc::server server(9999);

  server.bind("bug", []{
      using namespace std::chrono_literals;
      std::this_thread::sleep_for(2s);
    });

  server.run();
}
```

`client.cpp`
```c++
#include <iostream>

#include "rpc/client.h"
#include "rpc/rpc_error.h"

int main() {

  rpc::client client("localhost", 9999);
  client.set_timeout(50);

  try {
    client.call("bug");
  } catch(rpc::timeout& e) {
    std::cerr << e.what() << '\n';
  }
}
```

**Comment by sztomi** [comment]
Good find, and thanks for the detailed report. I will take a look and possibly fix it in the next release. Most likely, the server needs to have more checks around the connection, since this bug would be triggered in other circumstances as well.

**Comment by xaxousis** [comment]
Great, thank you very much !

**Comment by sztomi** [comment]
I was able to reproduce this bug. Trying to craft a good test case for it now. I wonder if there is a way to catch the exception outside the server.

```cpp
TEST(server_session_test_bug153, bug_153_crash_on_client_timeout) {
    rpc::server s("127.0.0.1", rpc::constants::DEFAULT_PORT);
    s.bind("bug_153", []() {
        std::this_thread::sleep_for(std::chrono::milliseconds(10));
        return 0;
    });
    s.async_run();

    auto client = std::unique_ptr<rpc::client>(new rpc::client("localhost", rpc::constants::DEFAULT_PORT));
    client->set_timeout(5);
  
    try {
        client->call("bug_153");
    } catch(rpc::timeout& ) {
        std::cout << "timeout\n";
        client.reset();
    }
    std::this_thread::sleep_for(std::chrono::milliseconds(20));
}
```
