### ISSUE TITLE
Calling functions with objects containing array and vectors

### ISSUE THREAD

**Issue by pelegn** [rpclib/rpclib#163]
Hi, 
I'm new to your project and trying to get how to work with it. I'm trying to pass over the rpc calls objects containing arrays and vectors. when i receive the object on the server side the vector is empty and the array is all zeros is there a way i need to pack them ?

Thanks

**Comment by sztomi** [comment]
Could you add your client and server code, particularly your struct definitions and how you call the functions?

**Comment by pelegn** [comment]
hey found the problem i had an old copy ctor from other test...sorry for the mess :)
but if i already asked is there a way to send an array that is not part of an object?

**Comment by sztomi** [comment]
That's alright. :)

> but if i already asked is there a way to send an array that is not part of an object?

Sure. I suggest using either an `std::array` or `std::vector` as a parameter. It should work fairly transparently.
