### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by NukeBird** [rpclib/rpclib#164]
Can I use rpclib on Android OS? How?

**Comment by sztomi** [comment]
Unfortunately, not at the moment, only Linux, macOS and Windows are supported. While rpclib is completely standards-compliant, the NDK is a hot mess and it's very hard to even compile rpclib with it. Another user was messing around and managed to get it to compile:, but unit tests were failing: https://github.com/rpclib/rpclib/issues/133

**Comment by sztomi** [comment]
What you *can* do, is use a java implementation of msgpack as a client or server running on Android. You can implement a corresponding server or client in C++ with rpclib and connect those.

**Comment by NukeBird** [comment]
@sztomi oh... Sad to hear it :( 

Is android support planned for the future?

**Comment by sztomi** [comment]
It might be, but I don't have an ETA. There is a lot of work to be done for 3.0 and supporting Android, given the state of the NDK probably won't make it before that.

**Comment by wzhou1974** [comment]
Does rpclib support Android now ?
I want to introduce rpclib in my project.

**Comment by meitalcohenyaacobi** [comment]
Does rpclib support Android now ?

**Comment by shakthi-prashanth-m** [comment]
@meitalcohenyaacobi @wzhou1974 
 #258 might be helpful, not sure. Worth giving a try.
