### ISSUE TITLE
rpc::server segfaults when the client unexpectedly dies

### ISSUE THREAD

**Issue by klemen-forstneric** [rpclib/rpclib#166]
Here's where it crashes:

https://github.com/rpclib/rpclib/blob/master/lib/rpc/detail/server_session.cc#L98

When server_session tries to execute `write_strand_.post` with the lambda it just segfaults. Here are the last three logs before the segfault happens:

```
2017-11-17 06:29:38.176  DEBUG   dispatcher      Dispatching call to 'Recognize' (/tmp/rpclib-2.2.0/lib/rpc/dispatcher.cc:44)
2017-11-17 06:29:38.219  INFO    session         Client disconnected
2017-11-17 06:29:38.219  INFO    session         Closing session.
```

I'm sorry I don't have an example which could be used to reproduce the bug.

**Comment by klemen-forstneric** [comment]
Investigated the crash a bit further. Maybe the problem is that you don't capture the `self` local variable in the lambdas and the last reference to `rpc::server_session` gets destroyed when `close` gets called?

**Comment by sztomi** [comment]
Excellent analysis, that should be passed in any case (even if it's not exactly what causes the crash). Are you able to reproduce the crash in your environment? If so, would you mind adding the self shared_ptr to the lambdas' capture lists (it might missing from other places) and see if it persists?

**Comment by klemen-forstneric** [comment]
Yup, I've added `self` to capture lists [here](https://github.com/rpclib/rpclib/blob/master/lib/rpc/detail/server_session.cc#L63) and [here](https://github.com/rpclib/rpclib/blob/master/lib/rpc/detail/server_session.cc#L99) and it doesn't seem to crash anymore. Would you like a pull request for this? 🙂

**Comment by sztomi** [comment]
Yes please, against the dev branch. Thanks a lot!

**Comment by klemen-forstneric** [comment]
No problem, [here](https://github.com/rpclib/rpclib/pull/167) it is.

**Comment by sztomi** [comment]
Thanks, I've merged it. I'm going to close this issue, but feel free to reopen if the crash resurfaces.
