### ISSUE TITLE
Doing push model with rpclib

### ISSUE THREAD

**Issue by sytelus** [rpclib/rpclib#168]
Ok... this is going to be bit off topic but its very important for us and very likely many other users. Basically, the question is how can we implement push model with rpclib? So we have server that wants to send out messages and client who listens to it. When message arrives, client should get an event where it would process it. 

In context of AirSim and other simulators/robotics systems, this is needed for middleware such as ROS. Virtually every 1 out 2 users of AirSim have requested ROS adapters and for us to built it, we need to have push as well as pull model.

It would be interesting know if this can already be done or if there is way to add this feature. I would be happy to contribute as well.

**Comment by sztomi** [comment]
There are a couple of options. 

1. Connect to the server and make an async call with the client. You can wait on the future indefinitely. When it returns, you can make the call again and wait. 

2. Create a dual connection: each client has a callback server. The connect to the server and "register" themselves, prompting the server to connect to their callback servers as a client. So both sides have a client and a server object. This way the server can make calls with high fidelity. This is the cleanest way you can do it now with rpclib. The bound function in the client's callback server is your "event".

**Comment by sytelus** [comment]
2nd option is definitely more cleaner. I'll try that out. Thanks.

**Comment by ahoarau** [comment]
I'd very much like to see this feature as well.
Could it be something like : 

```cpp
rpc::client c("localhost", 8080);
c.asyncEvent("NewIncomingData", [](string const& msg) {
    // New msg
  });
```

Using only the client, I see something like this : 

```cpp
rpc::client c("localhost", 8080);
auto pushNotificationThread = std::thread([&](){
    while(1){
       c.call("NewIncomingData", [](string const& msg) {
           // New msg
        });
    }
});
```

But it's putting too much load on the server.

**Comment by sztomi** [comment]
I wonder how other libraries do this. The `asyncEvent` example is pretty much like a "superclient", i.e. it contains a server. I'm not sure if there is any advantage to fusing the server and client on the library level, compared to letting users do it. Maybe sharing the TCP socket is valid, but in that case I'd rather allow reusing the transport layer (see #59).

**Comment by ahoarau** [comment]
I guess the only advantage is not having to instantiate a server with a new 'push port'.
That's not so much it's true, but it would be very convenient if it was included (/hidden) in the client
