### ISSUE TITLE
Linking library issues

### ISSUE THREAD

**Issue by EvyEh** [rpclib/rpclib#176]
Hello,

I am having problems with linking the static library to my executable, causing a whole slew of LNK2019 (unresolved external symbol) issues. How do I do this with Visual Studio?

**Comment by sztomi** [comment]
Please include a bit more information (like compiler output, which version of VS, how are trying to link it etc.).

**Comment by EvyEh** [comment]
I am using Visual Studio Community 2017. I included the path to the rpc headers in the additional include directories, which I think worked, since I was able to add the headers and write the code without errors popping up. When I build the code, I get this:
`1>------ Build started: Project: ThalmicServer, Configuration: Debug Win32 ------
1>ThalmicServer.obj : error LNK2019: unresolved external symbol "private: static void __cdecl rpc::detail::dispatcher::enforce_arg_count(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned int,unsigned int)" (?enforce_arg_count@dispatcher@detail@rpc@@CAXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@II@Z) referenced in function "public: class std::unique_ptr<class clmdep_msgpack::v1::object_handle,struct std::default_delete<class clmdep_msgpack::v1::object_handle> > __thiscall <lambda_df91d1daf68954d703124c188fa2c856>::operator()(struct clmdep_msgpack::v2::object const &)const " (??R<lambda_df91d1daf68954d703124c188fa2c856>@@QBE?AV?$unique_ptr@Vobject_handle@v1@clmdep_msgpack@@U?$default_delete@Vobject_handle@v1@clmdep_msgpack@@@std@@@std@@ABUobject@v2@clmdep_msgpack@@@Z)
1>ThalmicServer.obj : error LNK2019: unresolved external symbol "private: void __thiscall rpc::detail::dispatcher::enforce_unique_name(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?enforce_unique_name@dispatcher@detail@rpc@@AAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "public: void __thiscall rpc::detail::dispatcher::bind<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > (__cdecl*)(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)>(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > (__cdecl*)(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >))" (??$bind@P6A?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@@Z@dispatcher@detail@rpc@@QAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@P6A?AV34@V34@@Z@Z)
1>ThalmicServer.obj : error LNK2019: unresolved external symbol "public: __thiscall rpc::server::server(unsigned short)" (??0server@rpc@@QAE@G@Z) referenced in function _main
1>ThalmicServer.obj : error LNK2019: unresolved external symbol "public: __thiscall rpc::server::~server(void)" (??1server@rpc@@QAE@XZ) referenced in function _main
1>ThalmicServer.obj : error LNK2019: unresolved external symbol "public: void __thiscall rpc::server::async_run(unsigned int)" (?async_run@server@rpc@@QAEXI@Z) referenced in function _main
1>C:\Users\Er\source\repos\ThalmicLogger\Debug\ThalmicServer.exe : fatal error LNK1120: 5 unresolved externals
1>Done building project "ThalmicServer.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

I tried adding the path to the additional library directories as well, but that didn't cause any change. I'm completely stumped as to where the library I'm supposed to be linking is or how to do it at all. Thanks for the fast response btw :)

**Comment by sztomi** [comment]
You need to first build rpclib. After you did, you are supposed to have a rpc.lib file. In the case of visual studio you might need to build separate Debug/Release configs (even if you don't want to debug rpclib itself) because it won't let you link to the other. Then set the additional library paths to the directories containing the rpc.lib files (again, do this for Debug and Release configs). Then, add rpc.lib to the Additional Library Dependencies (It's under Settings->Linker->Input, I think).

**Comment by EvyEh** [comment]
That seems to have solved it! For any future people having this problem, the key things to set are Settings->Linker->General, Additional Library Directories (For me the path was \rpclib\build\Debug), and Settings->Linker->Input, Additional Dependencies rpc.lib.

Thanks for your help sztomi!
