### ISSUE TITLE
Errors when using latest ASIO (not part of dependencies)

### ISSUE THREAD

**Issue by sasmaster** [rpclib/rpclib#178]
Hi. I am trying to integrate rpclib into a project which already uses ASIO standalone lib. So I tried to strip the ASIO off from default dependenies.

I realized I had to change the macro for RPCLIB_ASIO to 'asio' .
But once I did it I had compiler error telling me that 

     RPCLIB_ASIO::strand  lacks template arguments.

And indeed I had to chance all the occurences of this varible to this:

    RPCLIB_ASIO::io_service::strand read_strand_;

I still haven't tested this build, but it at least compiles.I would suggest to lib's creator to remove default ASIO dependeny completely. ASIO lib is in active development.Also many network related projects use ASIO or (BOOST) ASIO in some capacity. As ASIO is header only lib ,I see no problem to ask the users to provide it as dependency, or even integrate the pull from its repo via CMAKE.

Thanks!

**Comment by sztomi** [comment]
I completely agree, as I commented on #179 . I'm closing this as duplicate.
