### ISSUE TITLE
Incompatible _WIN32_WINNT  enumerator when using with websocketpp lib

### ISSUE THREAD

**Issue by sasmaster** [rpclib/rpclib#180]
Hi. _WIN32_WINNT  macro cannot be set to _WIN32_WINNT=0x0501 ,when using the lib with websocketpp,for example.Since websocketpp uses  CancelIoEx which requires _WIN32_WINNT to be at least   0x0600

Thanks.

**Comment by sztomi** [comment]
Closing as duplicate of #179 (please comment on that issue if you have any more info instead of opening new issues).
