### ISSUE TITLE
How to build static with static runtime

### ISSUE THREAD

**Issue by bangusi** [rpclib/rpclib#195]
My environment is CentOS 7. g++ 6.3.  I need to build a static binary that will be used on a host (RedHat 7 ) that has an old c/c++ run-time that I cannot ( not allowed to ) to upgrade. Any guide / howto?

**Comment by sztomi** [comment]
I think your best bet is to bundle all .so files and set LD_LIBRARY_PATH to load them.

**Comment by orzel** [comment]
For the record, i use librpc.a in a static C++ program. All i had to do was to add -fPIC to CXX flags when building librpc. This can be done easily from ccmake.
