### ISSUE TITLE
how to use rpclib with arduino?

### ISSUE THREAD

**Issue by gitstar12** [rpclib/rpclib#203]
I want communicate between Airsim(which uses rpclib) and Arduino board. So how do I use the rpclib with arduino??

**Comment by sztomi** [comment]
I don't know if rpclib is suitable for embedded use-cases. It is probably not due to code bloat by C++ templates. I think you would be better of using a C library. rpclib implements msgpack-rpc, so any msgpack-rpc client and server can cooperate with rpclib clients and servers.
