### ISSUE TITLE
managing sessions and client disconnect

### ISSUE THREAD

**Issue by therealkenc** [rpclib/rpclib#207]
My RPC use-case requires per-client state to be maintained in the server. When a client disconnects, its state needs to be released. A well behaved client may send a `close()` style RPC, but this cannot be relied upon because the client might just die. What is the correct way to be notified of a client disconnect? Apologies if it is staring me in the face in the documentation.

**Comment by raymoo** [comment]
I couldn't find anything for this. Seems to me like the only option would be to have some kind of timeout and have the client call a heartbeat RPC.

**Comment by therealkenc** [comment]
Thanks. I timeout/heartbeat is indeed the only solution; and not because of `rpclib` but because of the nature of the transport (tcp). I should have clued that from the outset.

**Comment by raymoo** [comment]
No, it should be possible for rpclib to implement this on top of TCP, which does keep track of connections.

**Comment by therealkenc** [comment]
Only if you're local; otherwise you are starting down the barrel of 30 minutes of `tcp_retries2` when someone yanks a cable on some router between you and Timbuktu. But yes, at base you're right. I hacked up local [fork]([https://github.com/therealkenc/rpclib/commit/96a9887d59e03df546c80636627cd9a28ac165bc#diff-0bd857dcff573bab9132e2fa1f1ff0f0L133](https://github.com/therealkenc/rpclib)) that uses AF_UNIX and adds `session_end_callback` to [`server::close_session()`](https://github.com/therealkenc/rpclib/blob/local/lib/rpc/server.cc#L179).
