### ISSUE TITLE
Only librpc.a ?

### ISSUE THREAD

**Issue by VersusRain** [rpclib/rpclib#227]
need help!!!

I follow the step  on url : http://rpclib.net/compiling/  ,,,  but   ,  no "ouput" dir, only "librpc.a" created.

emmm.....that's  All?   and where's the  headers???
![adie vp9 ilt3g1x6bhm_w](https://user-images.githubusercontent.com/35909763/50391559-c80d4800-0781-11e9-9191-6ed366fe70ae.png)
![xha rnnrc 56 zhywx598m](https://user-images.githubusercontent.com/35909763/50391566-cba0cf00-0781-11e9-8ef9-50a3b7e01c76.png)
![qq 20181224134218](https://user-images.githubusercontent.com/35909763/50391590-d3f90a00-0781-11e9-88e7-5509afc0f2e1.png)

**Comment by goldsail** [comment]
@qchateau Your answer is correct. `librpc.a` alone is the output of the compilation. To use this library, first add the `include` folder to your include directories (it contains header files -- definition), and then link `librpc.a` to your C++ project (it is a binary file -- implementation).
