### ISSUE TITLE
Project still alive

### ISSUE THREAD

**Issue by MBalszun** [rpclib/rpclib#229]
I've only recently learned about this library and initial tests look very promising. However, given that the last commit seems to be over a year ago I was wondering if this project is still alive.

**Comment by Overv** [comment]
Given that issues [like these](https://github.com/rpclib/rpclib/issues/187) aren't being fixed this library does seem pretty much dead unfortunately :(

**Comment by qchateau** [comment]
I'm using this library actively and facing the lack of maintenance I made a fork in which I merged some of the interesting PR made here. I don't have time to actively develop rpclib but I have enough time to merge a few PR from time to times.

I wish this library could go back to active status as well...

**Comment by sztomi** [comment]
Regretfully, I don't have time to work on rpclib currently. I'd love to fix up the broken features and merge the good PRs but I just can't find the time. I do want to pick it up eventually, but can't make promises on timing. Sorry.

**Comment by qchateau** [comment]
In the meantime, feel free to use my fork (https://github.com/qchateau/rpclib.git), I basically merged a few interesting PR made to this repo, and added a few of my own changes.

**Comment by micfan** [comment]
oh, no...

**Comment by 111Moderato** [comment]
@qchateau 
Hi, Is there any function in the merged branch that can control the number of client connections? 

I know that worker threads can be set to limit it, but since the services I want involve the use of GPU memory, I want to limit the number of clients. Look forward to your reply

**Comment by qchateau** [comment]
I don't think so. Your service can simply deny the call though

**Comment by 111Moderato** [comment]
Okay, I'll think about it again.

**Comment by mquinson** [comment]
@sztomi why don't you add @qchateau to the members of the current project to simplify things and get the PR made against this repository directly merged here?

**Comment by qhaas** [comment]
Thanks for picking up the torch @qchateau !  We had been using the [CARLA maintained fork of rpclib](https://github.com/carla-simulator/rpclib), so hopefully between your fork and theirs, most of these outstanding issues can be addressed.

**Comment by qchateau** [comment]
To be fair I don't actively support rpclib anymore: I don't have a use for it anymore (I replaced it with my own lib https://github.com/qchateau/packio) and as I don't receive notifications for issues/PR on the main repo, I rarely check if there are pending PRs...

**Comment by sztomi** [comment]
Closing in favor of https://github.com/rpclib/rpclib/issues/273
