### ISSUE TITLE
how can i bind rpc::server to class's member function

### ISSUE THREAD

**Issue by fengshaoxia** [rpclib/rpclib#251]
```c
class test
{
public:
    void start()
    {
        m_sv.bind("show", &test::show); //error
        m_sv.run();
    }
    void show(std::string &s);
private:
    rpc::server m_sv{8080};
}
```
how can i bind `show` with `m_sv`? thanks.

**Comment by dossjh** [comment]
Hello,

You need to use lamdas.  This is how i do it:
`m_sv.bind("show", [this](std::string s){return this->login(s);});`

now that I think about it, I'm not sure how you would do that with a void.

**Comment by fengshaoxia** [comment]
@dossjh thanks
