### ISSUE TITLE
Renaming the project to rpclib

### ISSUE THREAD

**Issue by Roelli** [rpclib/rpclib#281]
Naming the project just rpc in cmake could collide with projects using it in their cmake environment. I would suggest to change it to rpclib to represent the library natrue of this project.

https://github.com/rpclib/rpclib/blob/b95ec2a2f488cd23832e7ecc80cede0e426d5322/CMakeLists.txt#L2

**Comment by sztomi** [comment]
> Naming the project just rpc in cmake could collide with projects using it in their cmake environment

I disagree. Any name could collide with anyone's codebase. So changing this line here would only solve the issue for that specific (if I understand correctly, theoretical) environment, and would create a similar issue for someone else. Avoiding name collisions is the responsibility of the project that consumes an upstream library. 

The solution is not to change this line here, but to rely on modern cmake features that make this a non-issue (i.e. avoid  `add_subdirectory` for dependencies and use imported targets with namespaced names).
