### ISSUE TITLE
how to enable logging?

### ISSUE THREAD

**Issue by ayushanand18** [rpclib/rpclib#312]
We are using `rpclib` for a university project, and went through the complete documentation.
But couldn't find a way to enable logging of internal calls be default. Is this something provided by this library or we need to write on our own?

If the latter is the case, any suggestions?

Thanks!

**Comment by sztomi** [comment]
Maybe you need `-DRPCLIB_ENABLE_LOGGING=ON`? https://github.com/rpclib/rpclib/blob/master/CMakeLists.txt#L23

**Comment by ayushanand18** [comment]
Thanks for the info! Where do the log get stored? Second, does this log runtime logs like IPs of requests or only stack traces of library function calls?

**Comment by sztomi** [comment]
It's been a while, but I think it only logs to the console. You can set the log level. If you search the source code, the various LOG_xxx calls are what will be logged. This is only for the library itself, i.e. to see if a requests is received, parsed, dispatched.

**Comment by ayushanand18** [comment]
Thanks so much for the info!
