### ISSUE TITLE
Change Documentation of Async Call

### ISSUE THREAD

**Issue by bowerscd** [rpclib/rpclib#89]
[In Docs](http://rpclib.net/cookbook/#calling-functions) - 

rpc.call_async

[In reality](https://github.com/rpclib/rpclib/blob/master/examples/mandelbrot/mandelbrot_client.cc),

rpc.async_call

**Comment by sztomi** [comment]
Right, thanks for spotting this. I'll fix it soon.

**Comment by sztomi** [comment]
This is now fixed on the dev branch. I'm going to close this when it's merged to master and the website is updated as well.

**Comment by sztomi** [comment]
1.0.0 has been released and the fix was merged to master. The website was also updated.
