### ISSUE TITLE
Connect Error ? or Timeout Exception or Timeout Options?

### ISSUE THREAD

**Issue by gggin** [rpclib/rpclib#91]
Hello, I found that if I close server, the client will always wait.
I don't think this is a good way.

I try to find a way to deal with this, but I found nothing.
So I ask the question here, thank you!

**Comment by sztomi** [comment]
Can you show me a code example of how you are using the client? 

There are a couple of options. There is [get_connection_state](http://rpclib.net/cookbook/#querying-the-connection-state). For getting a timeout while waiting for future responses, you can use [std::future::wait_for](http://en.cppreference.com/w/cpp/thread/future/wait_for). Maybe the docs should be more explicit about this. I'll take a note to add an example of this.

**Comment by gggin** [comment]
Thank you for your response and that help me.
I hope I can help this project a lot, but the code is first.
I read this project's code two days, I found that it's so great for me, I like `asio` and `c++14`.
So I will try to use this library.

I read the roadmap, the way is also good for me (like IPC, nodejs support, also user's own way(http or udp or some hardware) )

**Comment by sztomi** [comment]
I'm glad that helped. Please be aware that 1.0.0 is not released yet (I tagged the version and github treats it as a release, but it's not).
