### ISSUE TITLE
Allow extra flags to be passed for build

### ISSUE THREAD

**Issue by timotheecour** [rpclib/rpclib#92]
(without editing CmakeLists)

**Comment by sztomi** [comment]
For -fPIC and similar extra flags I already added a RPCLIB_EXTRA_BUILD_FLAGS parameter on a local dev branch, so that's coming soon. Shared library is currently not supported, but may be added in the future. Unfortunately to get these right now, you have to edit the CMakeLists.txt file.

**Comment by sztomi** [comment]
1.0.0 has been released and the fix was merged to master.
