### ISSUE TITLE
No timeout or error when calling non-existant function

### ISSUE THREAD

**Issue by dkozel** [rpclib/rpclib#97]
When I make a blocking call to a function which has not been bound on the server side no error is returned and the call never returns.

**Comment by sztomi** [comment]
There is a unit test for this which passes: https://github.com/rpclib/rpclib/blob/master/tests/rpc/dispatcher_test.cc#L163

Can you show me your code.

**Comment by dkozel** [comment]
Hello @sztomi. You're quite right, calling a non-existant function does throw an rpc::error. Sorry for the noise.

Thank you for making all your work on the library available. It has been very good to work with so far other than minor limitations of the MsgPack library (poor handling of enum classes).
