### ISSUE TITLE
Verify and document minimum compiler versions

### ISSUE THREAD

**Issue by sytelus** [rpclib/rpclib#99]
Just wondering what is the minimum GCC version supported for compiling rpclib? We are trying to compile [AirSim](http://github.com/Microsoft/AirSim) which has dependency on rpclib and it looks GCC 5.4 still gives us errors.

**Comment by sztomi** [comment]
Could you copy&paste the errors here? rpclib is compiled on Travis with the g++-5 package from ubuntu-toolchain-r-test, which I believe is exactly 5.4.

**Comment by sztomi** [comment]
It seems that Travis does use 5.4, so I'm guessing the issue is somewhere in your code. Travis builds not only the lib but also the unit tests, so the templates are also used during the compilation. Let me know if you still find that rpclib if failing to compile on this version of g++ still.
